name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyze-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.4'
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Generate Localizations
        run: flutter gen-l10n

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test
